#!/usr/bin/env python3
"""Generate the freestanding ColdFire unit (same pattern as Euclid)."""
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FLAGS = ['-mcpu=54454', '-msoft-float', '-O3', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer']

def text_bytes(source, td):
    """The .text an assembly source assembles to on 54454."""
    asm = pathlib.Path(td) / 'check.s'; obj = pathlib.Path(td) / 'check.o'; binary = pathlib.Path(td) / 'check.bin'
    asm.write_text(source)
    subprocess.run(['m68k-elf-as', '-mcpu=54454', str(asm), '-o', str(obj)], check=True)
    subprocess.run(['m68k-elf-objcopy', '-O', 'binary', '-j', '.text', str(obj), str(binary)], check=True)
    return binary.read_bytes()


def gcc_version():
    out = subprocess.run(['m68k-elf-gcc', '--version'], capture_output=True, text=True, check=True).stdout
    return out.splitlines()[0].split()[-1]


def written_with(source):
    """The gcc version recorded in a cpu.s header, or None for a file written
    before the header carried it."""
    m = re.match(r'\| Generated by generate_cpu\.py \(m68k-elf-gcc ([\d.]+)\)', source)
    return m.group(1) if m else None


def generate():
    subprocess.run([sys.executable, str(HERE/'generate_tables.py'), '--check'], check=True)
    with tempfile.TemporaryDirectory() as td:
        asm = pathlib.Path(td) / 'cpu.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-S', 'modules/tapeecho/cpu.c',
                        '-o', str(asm)], cwd=ROOT, check=True)
        source = (f'| Generated by generate_cpu.py (m68k-elf-gcc {gcc_version()}); edit cpu.c / cpu_hooks.s / cpu_kernels.s.\n'
                  # GNU as relaxes an external jra differently for ISA B and C.
                  # Pin external tail calls to the absolute jump used on 54454.
                  + re.sub(r'(?m)^\tjra (te_\w+)$', r'\tjmp \1', asm.read_text())
                  + '\n' + (HERE / 'cpu_hooks.s').read_text()
                  + '\n' + (HERE / 'cpu_kernels.s').read_text())
        if '*8)' in source:
            raise RuntimeError('scaled-*8 ColdFire address mode is hardware-unsafe (Vec 03)')
        asm.write_text(source)
        binaries=[]
        for cpu in ('54454','5475'):
            obj=pathlib.Path(td)/f'{cpu}.o'
            binary=pathlib.Path(td)/f'{cpu}.bin'
            subprocess.run(['m68k-elf-as',f'-mcpu={cpu}',str(asm),'-o',str(obj)],check=True)
            subprocess.run(['m68k-elf-objcopy','-O','binary','-j','.text',str(obj),str(binary)],check=True)
            binaries.append(binary.read_bytes())
        if binaries[0]!=binaries[1]:
            raise RuntimeError('54454 machine code differs from platform ISA-B encoding')
        return source

if __name__ == '__main__':
    source = generate()
    dest = HERE / 'cpu.s'
    if '--check' in sys.argv:
        # cpu.s is what ONE gcc emitted from cpu.c: another version emits
        # different code (16.2.0 here against the file committed 23 Sep 2026,
        # the label numbering and the machine code both differ), so the
        # comparison only means something under the recorded compiler.
        # Elsewhere the committed cpu.s is what the build assembles, and this
        # says so instead of calling it stale.
        committed = dest.read_text() if dest.exists() else ''
        recorded, local = written_with(committed), gcc_version()
        if not dest.exists():
            sys.exit('Tape Echo cpu.s is missing: run modules/tapeecho/generate_cpu.py')
        if recorded != local:
            print(f'  [SKIP] Tape Echo cpu.s was written by m68k-elf-gcc '
                  f'{recorded or "an unrecorded version"}; this machine has {local}, whose output '
                  f'differs -- the committed cpu.s is what the build assembles; regenerate under '
                  f'{recorded or "the author\'s gcc"} to compare')
            sys.exit(0)
        with tempfile.TemporaryDirectory() as td:
            if text_bytes(source, td) != text_bytes(committed, td):
                sys.exit('Tape Echo cpu.s is stale: run modules/tapeecho/generate_cpu.py')
        print('Tape Echo ColdFire machine code matches cpu.c, cpu_hooks.s and cpu_kernels.s')
    else:
        dest.write_text(source)
